version: '3.8'

services:
  transcription-app:
    build: .
    container_name: live-transcription
    ports:
      - "8009:8009"
    environment:
      # Whisper model: tiny, base, small, medium, large, ivrit-large-v3-turbo
      # OpenAI models: Smaller = faster but less accurate, Larger = slower but more accurate
      # ivrit-large-v3-turbo: Hebrew-optimized GGML model
      - WHISPER_MODEL=ivrit-large-v3-turbo
      - PORT=8009
    volumes:
      # Cache Whisper models to avoid re-downloading
      - whisper-models:/root/.cache/whisper
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  whisper-models:
    driver: local
